name: game-critics-web-container
services:
  server:
    build: .
    ports:
      - 80:80
      - 443:443
      - 5173:5173
    volumes:
      - ./api:/var/www/html/api
      - ./front:/var/www/html/front
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: